spring:
  application:
    name: Employee Awards Service
  
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_awards
    username: postgres
    password: ${PSQL_PASSWORD}
    driver-class-name: org.postgresql.Driver
  
  # JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate  # Liquibase управляет схемой, поэтому validate для безопасности
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false
  
  # Liquibase
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  
  # Загрузка файлов
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB

# Server
server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

# Logging
logging:
  level:
    root: INFO
    ru.t2.employeeawards: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE